name: Build Auralis APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Auralis
        run: |
          mkdir extracted
          unzip -q auralis.zip -d extracted

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install Gradle
        run: |
          DISTRIBUTION_URL=$(grep '^distributionUrl=' extracted/gradle/wrapper/gradle-wrapper.properties | cut -d'=' -f2- | sed 's/\\//g')

          echo "Gradle URL:"
          echo "$DISTRIBUTION_URL"

          mkdir -p "$HOME/gradle"

          curl -L "$DISTRIBUTION_URL" -o "$HOME/gradle/gradle.zip"

          unzip -q "$HOME/gradle/gradle.zip" -d "$HOME/gradle"

          GRADLE_HOME=$(find "$HOME/gradle" -maxdepth 1 -type d -name "gradle-*" | head -1)

          echo "Gradle home:"
          echo "$GRADLE_HOME"

          echo "$GRADLE_HOME/bin" >> "$GITHUB_PATH"

      - name: Check Gradle
        run: |
          gradle --version

      - name: Build APK
        working-directory: extracted
        run: |
          gradle assembleDebug --stacktrace

      - name: Find APK
        run: |
          echo "=== APK ==="
          find extracted -type f -name "*.apk" -print

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Auralis-APK
          path: "extracted/**/build/outputs/apk/**/*.apk"
